jar {
    archiveBaseName = project.name
}

dependencies {
    compileOnly("org.springframework:spring-web")

    testImplementation("com.fasterxml.jackson.core:jackson-core")
    testImplementation("com.fasterxml.jackson.core:jackson-databind")
    testImplementation("com.fasterxml.jackson.core:jackson-annotations")
    testImplementation("org.springframework:spring-web")
    testImplementation("junit:junit")
    testImplementation("org.junit.vintage:junit-vintage-engine")
}
