jar {
    archiveBaseName = project.name
}

compileJava.dependsOn(processResources)

dependencies {
    implementation project(":pws-client")
    compileOnly("org.apache.httpcomponents.client5:httpclient5")
    compileOnly("org.springframework.boot:spring-boot-autoconfigure")
    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")
}
